### ISSUE TITLE
Reorganización de menu lateral

### ISSUE THREAD

**Issue by alreyes01** [FST2015PM/Plataforma#60]
# **El menu actual es:**

- Usuarios y permisos
   - Usuarios
   - Roles
- Fuentes de datos
   - Extractores
   - Conjuntos
   - Capas
- Pueblos Mágicos
- Tableros
- Puntos de acceso
   - End Points
   - Llaves API
- Bitácora

# **Cambiar a:**

- Administración del sistema
  - Usuarios y permisos
       - Usuarios
       - Roles
  - Definición de fuentes de datos
       - Extractores
       - Conjuntos
       - Capas
  - Definición de Tableros de control
  - Puntos de acceso
       - End Points
       - Llaves API
  - Bitácora
- Pueblos Mágicos
  - Catálogo de PM
  - Tableros de análisis de PM

**Comment by haxdai** [comment]
Tres niveles ya no es adecuado por usabilidad para un menú lateral, son tres clicks para llegar a una opción. Déjame revisar cómo podemos acomodarlo a dos niveles en categorías. De lo contrario tendríamos que cambiarlo por una barra superior de menús.

**Comment by haxdai** [comment]
@alreyes01 Esta es la propuesta, cómo la vez? Salvo pasarla por diseño para que nos dé mejor vista.

<img width="512" alt="captura de pantalla 2017-06-23 a la s 14 06 04" src="https://user-images.githubusercontent.com/7064389/27496856-65f3ccda-581d-11e7-9b43-f6c9be4f00a2.png">
